
language: python
sudo: false
branches:
  only:
    - master
python:
  - "2.7"
install:
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
  #- rm -rf $HOME/miniconda
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q --yes conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n test-environment python=2.7 numpy scipy pytables nose
script:
  - source activate test-environment
  - python -c "import tables; print dir(tables)" 
  - nosetests
cache:
  - apt
  - directories:
    - $HOME/.cache/pip
    #- $HOME/miniconda
